services:
  backend:
    build: .
    image: pgo-backend-challenge
    container_name: pgo-backend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
